REGARCH-62 Legacy routes redirects
SlovakNationalGallery/register-architektury pull request #109
Opened 2020-09-28 20:29 UTC by eronisko

2020-09-29 13:16 UTC, igor-kamil reviewed
maybe I miss something. but where do you handle stripping `index.php/` from URL? except tests...
overall it looks very promising. but for "real world" urls like `/index.php/sk/uvod/kontakt.html` it wouldn't work till I remove `index.php/` from the address.

2020-09-29 13:16 UTC, igor-kamil commented on routes/web_legacy.php
> +Route::redirect('/sk/uvod/kontakt.html', '/oddelenie-architektury');
I would consider permanent redirect (to tell google to index new url) for all legacy routes.

```suggestion
Route::redirect('/sk/uvod/kontakt.html', '/oddelenie-architektury', 301);
```

But we can do it in the next step - after we check it covers urls properly.

2020-09-29 13:31 UTC, eronisko commented on routes/web_legacy.php
> +Route::redirect('/sk/uvod/kontakt.html', '/oddelenie-architektury');
@igor-kamil 
> where do you handle stripping index.php/ from URL?

As far as I understand, this stripping happens automatically in `php artisan serve` (dev server) and also in Nginx with the 'canonical' Nginx configuration: https://laravel.com/docs/7.x/deployment#nginx

I've tested this in dev and on regarch.webumenia.sk and it worked for me. But feel free to try it for yourself as I was testing it quite frantically 😅

2020-09-29 13:42 UTC, igor-kamil commented on routes/web_legacy.php
> +Route::redirect('/sk/uvod/kontakt.html', '/oddelenie-architektury');
I use [valet](https://laravel.com/docs/8.x/valet) for local development (nginx instead of `php artisan serve`) and it doesn't work like that for me. that `try_files $uri $uri/ /index.php?$query_string;` is just telling to pass whole uri as parameter for `index.php` - not about removing it from url. but it's possible to cover removing `index.php` in nginx virtual host config - so if you wanted to do it this way, I am ok with that. 
Once I already had to deal with the similar scenario and I ended up adding `removeIndexPhpFromUrl()` to `RouteServiceProvider` as covered in https://ma.ttias.be/remove-index-php-from-the-url-in-laravel/

2020-09-29 13:56 UTC, igor-kamil commented on routes/web_legacy.php
> +Route::redirect('/sk/uvod/kontakt.html', '/oddelenie-architektury');
sorry. only now I read properly - if it works on regarch.webumenia.sk - I have no further objections ;)

2020-09-29 14:34 UTC, igor-kamil commented on routes/web_legacy.php
> +Route::redirect('/sk/uvod/kontakt.html', '/oddelenie-architektury');
so I tested it on regarch.webumenia.sk and you are right -> it works. however it produces "ugly" url with remaining `index.php` inside - e.g. http://www.register-architektury.sk/index.php/sk/objekty/566-administratívna-budova-fondu-národnej-obnovy.html -> https://regarch.webumenia.sk/index.php/sk/objekt/116-administrativna-budova-fondu-narodnej-obnovy
so I propose to remove the `index.php` from url in `RouteServiceProvider` anyway.

2020-09-30 10:57 UTC, igor-kamil requested changes
https://github.com/SlovakNationalGallery/register-architektury/pull/109#discussion_r496768751

2020-09-30 15:56 UTC, eronisko commented
@igor-kamil looks like the redirects were not stripping off `/index.php` only for `/objekty` and `/architekti` urls, i.e. those going through the `LegacyRedirectController`. I've attempted to fix it and now I think it's behaving as it should.

2020-09-30 20:42 UTC, igor-kamil approved these changes
ready to go! I appreciate the tests + cover of "not found" scenario with search.

2020-09-30 20:42 UTC, igor-kamil commented on app/Http/Controllers/LegacyRedirectController.php
> +        return redirect("$rootUrl$url");
cool! this is nice hack!

2020-10-01 03:57 UTC, merged