Fix/autocomplete overflow
SlovakNationalGallery/register-architektury pull request #110
Opened 2020-09-29 12:42 UTC by igor-kamil

fix:
- autocomplete on mobile
- autocomplete for current locale

2020-09-29 13:22 UTC, eronisko requested changes
Almost there. I haven't checked the CSS changes locally, so just some notes on JS.

2020-09-29 13:22 UTC, eronisko commented on resources/sass/_overflow.scss
> -}
🙌

2020-09-29 13:22 UTC, eronisko commented on resources/js/components/search.js
> +        transform: ({architects}) => architects,
How about getting the `locale` higher up? Then you could do
```suggestion
		url: `/api/search-sugestions/?locale=${locale}&search=%QUERY`,
		wildcard: '%QUERY',
		transform: ({architects}) => architects,
```

BTW, You don't have to go with my suggestion, but I think you'll still have to `encodeURIComponent()` your `query` if you don't use the `wildcard` option

2020-09-29 13:22 UTC, eronisko commented on resources/views/articles/index.blade.php
> +                {{ $article->getFirstMedia()->img()->attributes(['class' => 'h-16rem img-fluid', 'width' => 'auto']) }}
I haven't tested this, but are you sure this is working as expected? Is it pulling the right image size? Is it not stretching anything in funny ways?

I'm just double-checking, because I've tried `img-fluid` a few times and it's never been the right class for these responsive images :D

2020-09-29 13:27 UTC, igor-kamil commented on resources/views/articles/index.blade.php
> +                {{ $article->getFirstMedia()->img()->attributes(['class' => 'h-16rem img-fluid', 'width' => 'auto']) }}
to be honest... I don't know whether it will not introduce new issue :see_no_evil: 
but it is necessary to make it work on mobile - otherwise image doesnt have `max-width: 100%` and it overflows the container in not nice way... 
for me it looks fine so far

2020-09-30 10:49 UTC, eronisko approved these changes

2020-09-30 10:56 UTC, merged